### ISSUE TITLE
Installing plugin using docker compose

### ISSUE THREAD

**Issue by patrick-5546** [meln5674/grafana-mongodb-community-plugin#12]
I am getting the following error trying to install this plugin:
```
Error: ✗ /plugins/repo/meln5674-mongodb-community=https:/github.com/meln5674/grafana-mongodb-community-plugin/releases/download/v0.1.2/meln5674-mongodb-community.zip does not exist (Grafana v9.4.7 linux-amd64)
```

This is my docker compose file:
```yml
  grafana:
    image: grafana/grafana-enterprise:latest
    restart: unless-stopped
    ports
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    environment:
      - "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=meln5674-mongodb-community"
      - "GF_INSTALL_PLUGINS=meln5674-mongodb-community=https://github.com/meln5674/grafana-mongodb-community-plugin/releases/download/v0.1.2/meln5674-mongodb-community.zip"
```

Any idea what might be happening? It seems like the URL is not being passed through properly, as there is only one `/` after `https:`, but I'm not sure if this would cause the error.
